services:
  app:
    build:
      context: .
      dockerfile: docker/prod/Dockerfile
    volumes:
      - app-storage:/var/www/html/storage
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=pgsql
      - DB_PORT=5432
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - RUN_SEEDER=${RUN_SEEDER:-false}
      - PHP_POST_MAX_SIZE=100M
      - PHP_UPLOAD_MAX_FILE_SIZE=100M
      - PUSHER_APP_ID=${PUSHER_APP_ID}
      - PUSHER_APP_KEY=${PUSHER_APP_KEY}
      - PUSHER_APP_SECRET=${PUSHER_APP_SECRET}
      - PUSHER_APP_CLUSTER=${PUSHER_APP_CLUSTER}
      - PUSHER_HOST=soketi.domnek.de
      - PUSHER_HOST_FROM_CLIENT=soketi.domnek.de
      - PUSHER_PORT=443
      - PUSHER_SCHEME=https

    restart: always
    depends_on:
      pgsql:
        condition: service_healthy
    networks:
      - traefik_proxy
      - internal
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.ttc-app-rtr.entrypoints=https"
      - "traefik.http.routers.ttc-app-rtr.rule=Host(`tabletopcast.domnek.de`)"
      - "traefik.http.routers.ttc-app-rtr.tls=true"
      - "traefik.http.routers.ttc-app-rtr.tls.certresolver=lets-encrypt"
      # Middlewares
      - "traefik.http.routers.ttc-app-rtr.middlewares=chain-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.ttc-app-rtr.service=ttc-app-svc"
      - "traefik.http.services.ttc-app-svc.loadbalancer.server.port=8080"

  pgsql:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      PGUSER: ${DB_USERNAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-secret}
    ports:
      - 5555:5432
    volumes:
      - 'pgsql:/var/lib/postgresql/data'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-q" ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: always
    networks:
      - internal

  soketi:
    image: 'quay.io/soketi/soketi:latest-16-alpine'
    environment:
      SOKETI_DEBUG: "0"
    networks:
      - internal
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      # HTTP Routers
      - "traefik.http.routers.ttc-soketi-rtr.entrypoints=https"
      - "traefik.http.routers.ttc-soketi-rtr.rule=Host(`soketi.domnek.de`)"
      - "traefik.http.routers.ttc-soketi-rtr.tls=true"
      - "traefik.http.routers.ttc-soketi-rtr.tls.certresolver=lets-encrypt"
      # Middlewares
      - "traefik.http.routers.ttc-soketi-rtr.middlewares=chain-no-auth@file"
      # HTTP Services
      - "traefik.http.routers.ttc-soketi-rtr.service=ttc-soketi-svc"
      - "traefik.http.services.ttc-soketi-svc.loadbalancer.server.port=6001"

volumes:
  pgsql:
  app-storage:

networks:
  internal:
    external: false
  traefik_proxy:
    external: true
